on:
  workflow_dispatch:
    inputs:
      entry:
        type: string
        required: true

jobs:
  add-entry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: append entry
        run: echo "${{ inputs.entry }}" >> journal/journal.txt
      - name: commit entry
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "automated: add journal entry"
          git push
